# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          repository: wenersoft/.github
          path: ./.github
          
      - name: TICS Action
        uses: ./.github/actions/tics
        env: 
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          projectName: 'TICSDOCK'
          branchName: 'master'
          branchDir: 'tics_dock.py'
          ticsViewerUrl: 'http://localhost:42506/tiobeweb/TICS/'
          ticsAuthToken: ${{secret.TICSVIEWER}}
          #branchDir: '/home/danai/Tics-Plugins/testing-2'
          #ticsViewerUrl: 'http://localhost:20212/tiobeweb/2021.2/'
          clientToken: 'githubToken'
