# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          repository: wenersoft/.github
          path: ./.github
          
      - name: TICS Action
        uses: ./.github/actions/tics
        env: 
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          projectName: 'TiCS-Action'                                        # mandatory, default value is the project name that this action is running on
          branchName: 'andriopoulou-danai-patch-1'                          # mandatory, default value is the branch name that this action is running on
          branchDir: '/home/danai/Tics-Plugins/TICS-Action-1/TICS-Action'     # mandatory
          ticsViewerUrl: 'http://localhost:20212/tiobeweb/2021.2/'          # mandatory
          clientToken: 'githubToken'                                        # mandatory, the user token for the TiCS Viewer
